run:
  tests: false
  go: '1.24'
issues:
  exclude-files:
    - 'wire_gen.go'
  exclude-dirs:
    - docs
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gci:
    sections:
      - standard
      - default
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dupl
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - nolintlint
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - copyloopvar
    - whitespace
