version: "2"
run:
  go: "1.26"
  tests: false
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dupl
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - wire_gen.go
      - docs
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
  exclusions:
    generated: lax
    paths:
      - wire_gen.go
      - docs
      - third_party$
      - builtin$
      - examples$
