package avro1a

// Code generated by avro/gen. DO NOT EDIT.

import (
	"time"
)

// AddressRecord is a generated struct.
type AddressRecord struct {
	StreetNumber    string  `avro:"streetNumber" json:"street_number" yaml:"StreetNumber"`
	StreetName      string  `avro:"streetName" json:"street_name" yaml:"StreetName"`
	UnitNumber      *string `avro:"unitNumber" json:"unit_number" yaml:"UnitNumber"`
	PostalCode      string  `avro:"postalCode" json:"postal_code" yaml:"PostalCode"`
	City            string  `avro:"city" json:"city" yaml:"City"`
	StateOrProvince string  `avro:"stateOrProvince" json:"state_or_province" yaml:"StateOrProvince"`
	Country         string  `avro:"country" json:"country" yaml:"Country"`
	Latitude        float32 `avro:"latitude" json:"latitude" yaml:"Latitude"`
	Longitude       float32 `avro:"longitude" json:"longitude" yaml:"Longitude"`
}

// ImageRecord is a generated struct.
type ImageRecord struct {
	ID      string  `avro:"id" json:"id" yaml:"Id"`
	Index   int     `avro:"index" json:"index" yaml:"Index"`
	Caption *string `avro:"caption" json:"caption" yaml:"Caption"`
	URL     *string `avro:"url" json:"url" yaml:"Url"`
}

// AryeoFloorplanRecord is a generated struct.
type AryeoFloorplanRecord struct {
	URL string `avro:"url" json:"url" yaml:"Url"`
	// Id(uuid v7) of the underlying Aryeo Floorplan Record.
	ID string `avro:"id" json:"id" yaml:"Id"`
}

// AryeoListingRecord is a generated struct.
type AryeoListingRecord struct {
	// Id(uuid v7) of the underlying Aryeo Listing.
	ID string `avro:"id" json:"id" yaml:"Id"`
	// Id(uuid v7) of Aryeo Listing's underlying Company.
	CompanyID string `avro:"companyId" json:"company_id" yaml:"CompanyId"`
	// Timestamp depicting when Aryeo's listing was delivered.
	DeliveredAtDateTimeUtc time.Time `avro:"deliveredAtDateTimeUtc" json:"delivered_at_date_time_utc" yaml:"DeliveredAtDateTimeUtc"`
	// Enum depicting type of event.
	EventType string `avro:"eventType" json:"event_type" yaml:"EventType"`
	// Unique identifier of Showcase Engagement associated to underlying Aryeo Listing.
	EngagementID *string `avro:"engagementId" json:"engagement_id" yaml:"EngagementId"`
	// Address associated to Aryeo Listing.
	Address AddressRecord `avro:"address" json:"address" yaml:"Address"`
	// Photos delivered for underlying Aryeo Listing.
	Images *[]ImageRecord `avro:"images" json:"images" yaml:"Images"`
	// Floorplans associated to Aryeo Listing.
	Floorplans *[]AryeoFloorplanRecord `avro:"floorplans" json:"floorplans" yaml:"Floorplans"`
}
