// Code generated by avro/gen. DO NOT EDIT.
package main

// DummyEvent is a generated struct.
type DummyEvent struct {
	IntField             int     `avro:"IntField"`
	DoubleField          float64 `avro:"DoubleField"`
	StringField          string  `avro:"StringField"`
	BoolField            bool    `avro:"BoolField"`
	BytesField           []byte  `avro:"BytesField"`
	NewFieldWithDefault  *string `avro:"NewFieldWithDefault"`
	NewFieldWithDefault2 *string `avro:"NewFieldWithDefault2"`
}
