// Code generated by avrogen. DO NOT EDIT.

package heetch1

import (
	"github.com/heetch/avro/avrotypegen"
)

type DummyEvent struct {
	IntField    int
	DoubleField float64
	StringField string
	BoolField   bool
	BytesField  []byte
}

// AvroRecord implements the avro.AvroRecord interface.
func (DummyEvent) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"IntField","type":"int"},{"name":"DoubleField","type":"double"},{"name":"StringField","type":"string"},{"name":"BoolField","type":"boolean"},{"name":"BytesField","type":"bytes"}],"name":"DummyEvent","type":"record"}`,
		Required: []bool{
			0: true,
			1: true,
			2: true,
			3: true,
			4: true,
		},
	}
}
