// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.27.0
// source: schema_1.proto

package proto1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntField    int64   `protobuf:"varint,1,opt,name=IntField,proto3" json:"IntField,omitempty"`
	DoubleField float32 `protobuf:"fixed32,2,opt,name=DoubleField,proto3" json:"DoubleField,omitempty"`
	StringField string  `protobuf:"bytes,3,opt,name=StringField,proto3" json:"StringField,omitempty"`
	BoolField   bool    `protobuf:"varint,4,opt,name=BoolField,proto3" json:"BoolField,omitempty"`
	BytesField  []byte  `protobuf:"bytes,5,opt,name=BytesField,proto3" json:"BytesField,omitempty"`
}

func (x *DummyEvent) Reset() {
	*x = DummyEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DummyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyEvent) ProtoMessage() {}

func (x *DummyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyEvent.ProtoReflect.Descriptor instead.
func (*DummyEvent) Descriptor() ([]byte, []int) {
	return file_schema_1_proto_rawDescGZIP(), []int{0}
}

func (x *DummyEvent) GetIntField() int64 {
	if x != nil {
		return x.IntField
	}
	return 0
}

func (x *DummyEvent) GetDoubleField() float32 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *DummyEvent) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *DummyEvent) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *DummyEvent) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

var File_schema_1_proto protoreflect.FileDescriptor

var file_schema_1_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x65, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xaa, 0x01, 0x0a, 0x0a,
	0x44, 0x75, 0x6d, 0x6d, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x49, 0x6e,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6f,
	0x6f, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x42,
	0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x31, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_1_proto_rawDescOnce sync.Once
	file_schema_1_proto_rawDescData = file_schema_1_proto_rawDesc
)

func file_schema_1_proto_rawDescGZIP() []byte {
	file_schema_1_proto_rawDescOnce.Do(func() {
		file_schema_1_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_1_proto_rawDescData)
	})
	return file_schema_1_proto_rawDescData
}

var file_schema_1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_1_proto_goTypes = []interface{}{
	(*DummyEvent)(nil), // 0: evolution.DummyEvent
}
var file_schema_1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_1_proto_init() }
func file_schema_1_proto_init() {
	if File_schema_1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DummyEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_1_proto_goTypes,
		DependencyIndexes: file_schema_1_proto_depIdxs,
		MessageInfos:      file_schema_1_proto_msgTypes,
	}.Build()
	File_schema_1_proto = out.File
	file_schema_1_proto_rawDesc = nil
	file_schema_1_proto_goTypes = nil
	file_schema_1_proto_depIdxs = nil
}
