package avro2

// Code generated by avro/gen. DO NOT EDIT.

import (
	"time"
)

// InteractiveContentRecord is a generated struct.
type InteractiveContentRecord struct {
	URL string `avro:"url"`
}

// AryeoListingRecord is a generated struct.
type AryeoListingRecord struct {
	// Id(uuid v7) of the underlying Aryeo Listing.
	ID string `avro:"id"`
	// Timestamp depicting when Aryeo's listing was delivered.
	DeliveredAtDateTimeUtc time.Time `avro:"deliveredAtDateTimeUtc"`
	// Enum depicting type of event.
	EventType string `avro:"eventType"`
	// InteractiveContent associated to Aryeo Listing.
	InteractiveContent *[]InteractiveContentRecord `avro:"interactiveContent"`
}
