// Code generated by avro/gen. DO NOT EDIT.
package avro2

// InteractiveContentRecord is a generated struct.
type InteractiveContentRecord struct {
	URL   string `avro:"url"`
	IsImx *bool  `avro:"isImx"`
}

// Event is a generated struct.
type Event struct {
	InteractiveContent *[]InteractiveContentRecord `avro:"interactiveContent"`
}
