// Code generated by avro/gen. DO NOT EDIT.
package avro2

import (
	"time"
)

// InteractiveContentRecord is a generated struct.
type InteractiveContentRecord struct {
	URL   string `avro:"url"`
	IsImx *bool  `avro:"isImx"`
}

// Event is a generated struct.
type Event struct {
	ID                     string                      `avro:"id"`
	DeliveredAtDateTimeUtc time.Time                   `avro:"deliveredAtDateTimeUtc"`
	EventType              string                      `avro:"eventType"`
	InteractiveContent     *[]InteractiveContentRecord `avro:"interactiveContent"`
}
