package main

// Code generated by avro/gen. DO NOT EDIT.

// DummyEvent is a generated struct.
type DummyEvent struct {
	IntField    int     `avro:"IntField" json:"int_field" yaml:"IntField"`
	DoubleField float64 `avro:"DoubleField" json:"double_field" yaml:"DoubleField"`
	StringField string  `avro:"StringField" json:"string_field" yaml:"StringField"`
	BoolField   bool    `avro:"BoolField" json:"bool_field" yaml:"BoolField"`
	BytesField  []byte  `avro:"BytesField" json:"bytes_field" yaml:"BytesField"`
}
