package avro1

// Code generated by avro/gen. DO NOT EDIT.

import (
	"time"
)

// Event is a generated struct.
type Event struct {
	ID                     string    `avro:"id"`
	DeliveredAtDateTimeUtc time.Time `avro:"deliveredAtDateTimeUtc"`
	EventType              string    `avro:"eventType"`
}
