// Code generated by avrogen. DO NOT EDIT.

package avro1

import (
	"fmt"
	"github.com/heetch/avro/avrotypegen"
	"strconv"
)

type AryeoListingEventType int

const (
	AryeoListingEventTypeListingcreated AryeoListingEventType = iota
	AryeoListingEventTypeListingassociated
	AryeoListingEventTypeListingmedidelivered
)

var _AryeoListingEventType_strings = []string{
	"listingCreated",
	"listingAssociated",
	"listingMediDelivered",
}

// String returns the textual representation of AryeoListingEventType.
func (e AryeoListingEventType) String() string {
	if e < 0 || int(e) >= len(_AryeoListingEventType_strings) {
		return "AryeoListingEventType(" + strconv.FormatInt(int64(e), 10) + ")"
	}
	return _AryeoListingEventType_strings[e]
}

// MarshalText implements encoding.TextMarshaler
// by returning the textual representation of AryeoListingEventType.
func (e AryeoListingEventType) MarshalText() ([]byte, error) {
	if e < 0 || int(e) >= len(_AryeoListingEventType_strings) {
		return nil, fmt.Errorf("AryeoListingEventType value %d is out of bounds", e)
	}
	return []byte(_AryeoListingEventType_strings[e]), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
// by expecting the textual representation of AryeoListingEventType.
func (e *AryeoListingEventType) UnmarshalText(data []byte) error {
	// Note for future: this could be more efficient.
	for i, s := range _AryeoListingEventType_strings {
		if string(data) == s {
			*e = AryeoListingEventType(i)
			return nil
		}
	}
	return fmt.Errorf("unknown value %q for AryeoListingEventType", data)
}

type AryeoListingRecord struct {
	// Id(uuid v7) of the underlying Aryeo Listing
	Id string `json:"id"`

	// Timestamp depicting when Aryeo's listing was delivered
	Deliveredatdatetimeutc int64 `json:"deliveredAtDateTimeUtc"`

	// Enum depicting type of event
	Eventtype AryeoListingEventType `json:"eventType"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (AryeoListingRecord) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"doc":"Id(uuid v7) of the underlying Aryeo Listing","name":"id","type":"string"},{"doc":"Timestamp depicting when Aryeo's listing was delivered","name":"deliveredAtDateTimeUtc","type":{"logicalType":"timestamp-millis","type":"long"}},{"doc":"Enum depicting type of event","name":"eventType","type":{"default":"listingCreated","name":"AryeoListingEventType","symbols":["listingCreated","listingAssociated","listingMediDelivered"],"type":"enum"}}],"name":"com.zillowgroup.rmx.pem_schema.AryeoListingRecord","type":"record"}`,
		Required: []bool{
			0: true,
			1: true,
			2: true,
		},
	}
}
