// Code generated by avrogen. DO NOT EDIT.

package avro1

import (
	"github.com/heetch/avro/avrotypegen"
)

type Event struct {
	Interactivecontent *[]InteractiveContentRecord `json:"interactiveContent"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (Event) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"default":null,"name":"interactiveContent","type":["null",{"items":{"fields":[{"name":"url","type":"string"}],"name":"InteractiveContentRecord","type":"record"},"type":"array"}]}],"name":"com.zillowgroup.Event","type":"record"}`,
	}
}

type InteractiveContentRecord struct {
	Url string `json:"url"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (InteractiveContentRecord) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"url","type":"string"}],"name":"com.zillowgroup.InteractiveContentRecord","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}
