package aryeopem2

// Code generated by avro/gen. DO NOT EDIT.

// AddressRecord is a generated struct.
type AddressRecord struct {
	StreetNumber    string  `avro:"streetNumber"`
	StreetName      string  `avro:"streetName"`
	UnitNumber      *string `avro:"unitNumber"`
	PostalCode      string  `avro:"postalCode"`
	City            string  `avro:"city"`
	StateOrProvince string  `avro:"stateOrProvince"`
	Country         string  `avro:"country"`
	Latitude        float32 `avro:"latitude"`
	Longitude       float32 `avro:"longitude"`
}

// ImageRecord is a generated struct.
type ImageRecord struct {
	ID                        string  `avro:"id"`
	Index                     int     `avro:"index"`
	Caption                   *string `avro:"caption"`
	URL                       *string `avro:"url"`
	Filename                  *string `avro:"filename"`
	PhotographerAttributionID *string `avro:"photographerAttributionId"`
}

// InteractiveContentRecord is a generated struct.
type InteractiveContentRecord struct {
	URL   string `avro:"url"`
	IsImx *bool  `avro:"isImx"`
}

// OrderRecord is a generated struct.
type OrderRecord struct {
	// Id(uuid v7) of the Aryeo Listing order.
	ID    string `avro:"id"`
	IsImx bool   `avro:"isImx"`
}

// AryeoMediaDeliveredRecord is a generated struct.
type AryeoMediaDeliveredRecord struct {
	EventID   string `avro:"eventId"`
	EventType string `avro:"eventType"`
	ListingID string `avro:"listingId"`
	// Id(uuid v7) of Aryeo Listing's underlying Company.
	CompanyID string `avro:"companyId"`
	// Address associated to Aryeo Listing.
	Address AddressRecord `avro:"address"`
	// Photos delivered for underlying Aryeo Listing.
	Images *[]ImageRecord `avro:"images"`
	// InteractiveContent associated to Aryeo Listing.
	InteractiveContent *[]InteractiveContentRecord `avro:"interactiveContent"`
	// Orders associated to Aryeo Listing.
	Orders     *[]OrderRecord `avro:"orders"`
	BrandID    *string        `avro:"brandId"`
	IsShowcase *bool          `avro:"isShowcase"`
	AgentEmail *string        `avro:"agentEmail"`
}
